#!/bin/bash
# merge-values.sh - Merges three-layer Helm values for a tenant
# Usage: ./scripts/merge-values.sh <tenant-name>
# Example: ./scripts/merge-values.sh customer1-dev

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(dirname "$SCRIPT_DIR")"

TENANT_NAME="${1:-}"

if [[ -z "$TENANT_NAME" ]]; then
    echo "Error: Tenant name required"
    echo "Usage: $0 <tenant-name>"
    exit 1
fi

TENANT_DIR="$REPO_ROOT/tenants/$TENANT_NAME"

if [[ ! -d "$TENANT_DIR" ]]; then
    echo "Error: Tenant directory not found: $TENANT_DIR"
    exit 1
fi

# Extract env type from tenant name
# dev-john -> dev, customer1-dev -> dev, customer1-qa -> qa
get_env_type() {
    local tenant="$1"
    if [[ "$tenant" == dev-* ]]; then
        echo "dev"
    elif [[ "$tenant" == *-dev ]]; then
        echo "dev"
    elif [[ "$tenant" == *-qa ]]; then
        echo "qa"
    elif [[ "$tenant" == *-staging ]]; then
        echo "staging"
    elif [[ "$tenant" == *-prod ]]; then
        echo "prod"
    else
        echo "Error: Cannot determine env type from tenant name: $tenant" >&2
        exit 1
    fi
}

ENV_TYPE=$(get_env_type "$TENANT_NAME")

echo "Merging values for tenant: $TENANT_NAME (env-type: $ENV_TYPE)"

BASES_VALUES="$REPO_ROOT/bases/values.yaml"
ENV_TYPE_VALUES="$REPO_ROOT/env-types/$ENV_TYPE/values.yaml"
ENV_TYPE_CONFIG="$REPO_ROOT/env-types/$ENV_TYPE/config.json"
TENANT_OVERRIDES="$TENANT_DIR/overrides.yaml"
TENANT_VALUES="$TENANT_DIR/values.yaml"
TENANT_CONFIG="$TENANT_DIR/config.json"

# Check required files exist
for file in "$BASES_VALUES" "$ENV_TYPE_VALUES" "$ENV_TYPE_CONFIG"; do
    if [[ ! -f "$file" ]]; then
        echo "Error: Required file not found: $file"
        exit 1
    fi
done

# Create overrides.yaml if it doesn't exist
if [[ ! -f "$TENANT_OVERRIDES" ]]; then
    echo "# Layer 3: Tenant-specific overrides for $TENANT_NAME" > "$TENANT_OVERRIDES"
    echo "global:" >> "$TENANT_OVERRIDES"
    echo "  namespace: ns-$TENANT_NAME" >> "$TENANT_OVERRIDES"
fi

# Merge YAML files using yq
# Layer order: bases -> env-type -> tenant overrides
echo "# Merged values for tenant: $TENANT_NAME" > "$TENANT_VALUES"
echo "# Generated by CI - DO NOT EDIT MANUALLY" >> "$TENANT_VALUES"
echo "# Layers: bases/values.yaml + env-types/$ENV_TYPE/values.yaml + tenants/$TENANT_NAME/overrides.yaml" >> "$TENANT_VALUES"
echo "# Generated at: $(date -u +"%Y-%m-%dT%H:%M:%SZ")" >> "$TENANT_VALUES"
echo "" >> "$TENANT_VALUES"

if command -v yq &> /dev/null; then
    yq eval-all 'select(fileIndex == 0) * select(fileIndex == 1) * select(fileIndex == 2)' \
        "$BASES_VALUES" \
        "$ENV_TYPE_VALUES" \
        "$TENANT_OVERRIDES" >> "$TENANT_VALUES"
else
    echo "Warning: yq not installed. Using simple concatenation (manual merge may be needed)"
    cat "$BASES_VALUES" >> "$TENANT_VALUES"
    echo "---" >> "$TENANT_VALUES"
    cat "$ENV_TYPE_VALUES" >> "$TENANT_VALUES"
    echo "---" >> "$TENANT_VALUES"
    cat "$TENANT_OVERRIDES" >> "$TENANT_VALUES"
fi

# Generate config.json for ApplicationSet
# Read versions from env-type config and add tenant-specific fields
if command -v jq &> /dev/null; then
    jq --arg tenant "$TENANT_NAME" \
       --arg ns "ns-$TENANT_NAME" \
       --arg env "$ENV_TYPE" \
       '. + {tenant: $tenant, namespace: $ns, envType: $env} |
        .services.ui.enabled = true |
        .services.billing.enabled = true' \
        "$ENV_TYPE_CONFIG" > "$TENANT_CONFIG"
else
    echo "Warning: jq not installed. Cannot generate config.json"
    exit 1
fi

echo "Generated: $TENANT_VALUES"
echo "Generated: $TENANT_CONFIG"
echo "Done!"
