apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: prod
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Production environments - strict restrictions
  sourceRepos:
    - 'https://github.com/ctera-insight/*'
  destinations:
    - namespace: 'ns-*-prod'
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: ''
      kind: Namespace
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
  orphanedResources:
    warn: true
  syncWindows:
    # Only allow deployments during maintenance windows
    - kind: allow
      schedule: '0 2-6 * * 0'
      duration: 4h
      applications:
        - '*'
    - kind: deny
      schedule: '0 0-2,6-23 * * *'
      duration: 20h
      applications:
        - '*'
