apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: qa
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: QA environments - moderate restrictions
  sourceRepos:
    - 'https://github.com/ctera-insight/*'
  destinations:
    - namespace: 'ns-*-qa'
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: ''
      kind: Namespace
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
  orphanedResources:
    warn: true
